[project]
name = "ui"
version = "1.0.0"
description = "Simple frontend for SageCompass"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.3.0",
    "langgraph-sdk>=0.3.2",
]
